version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=Go-Server-Docker
      - APP_VERSION=0.0.1:docker
    ports:
      - "3000:3000" 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - new
    env_file:
      - docker.env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - new
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - new
    volumes:
      - ./migrations:/migrations  # Локальная папка с миграциями
    command: ["-path", "/migrations", "-database", "postgres://postgres:1234@db:5432/appdb?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
    links: 
      - db

networks:
  new:
